apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1 # Pod's name
  labels:
    tier: frontend
    environment: prod
spec:
  containers:
    - name: nginx-container
      image: nginx:stable-alpine
