apiVersion: v1
kind: Pod
metadata:
  name: host-path
spec:
  containers:
    - name: nginx-ctr
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/config
          name: my-host-path-volume
    - name: busybox-ctr
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do sleep 30; done;"]
  volumes:
  - name: my-host-path-volume
    hostPath:
      path: /tmp
