apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-ctr
      image: nginx
    - name: busybox-ctr
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep 5m"]

