apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-ambassador
spec:
  containers:
    - name: mysql-proxy-ctr
      image: mysql-proxy:latest
      ports:
      - containerPort: 3306
      env:
        - name: DB_HOST
          value: <DB_URL>
    - name: nginx-ctr
      image: nginx:latest
