apiVersion: v1
kind: Pod
metadata:
  annotations:
    tier: webserver
  name: nginx-pod-a # Pod's name
  labels:
    environment: prod
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:stable-alpine
