apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-headless
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 80
    protocal: TCP
    targetPort: 80
  selector:
    run: nginx-clusterip
