apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-liveness-command
spec:
  containers:
  - name: nginx-ctr-liveness-command
    image: nginx:latest
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      exec:
        command:
          - cat
          - /hello/world
