apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-liveness
spec:
  containers:
  - name: nginx-ctr-liveness
    image: nginx:latest
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: /healthcheck # check this path every 5 sec.
        port: 80
        httpHeaders:
        - name: my-custom-header
          value: my-custom-header-value
