apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-bare
  labels:
    app: nginx
    env: test
spec:
  containers:
    - image: nginx
      name: nginx-ctr-bare
      ports:
        - containerPort: 80
