apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replica-example
spec:
  replicas: 2
  selector:
    app: nginx
    environment: test
  template:
    metadata:
      labels:
        app: nginx
        environment: test
    spec:
      containers:
        - image: nginx
          name: nginx-ctr
          ports:
            - containerPort: 80
