apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx-ctr
      volumeMounts:
        - mountPath: "/var/www/html"
          name: my-pvc
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-hostpath-pvc
