apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-hostpath-pvc
  namespace: dynamic-storage
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-storage
  namespace: dynamic-storage
spec:
  containers:
    - image: nginx:stable
      name: nginx-ctr
      volumeMounts:
        - mountPath: "/var/www/html"
          name: my-pv
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-dynamic-hostpath-pvc
