apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-hostpath-pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #selector:
    #matchLabels:
      #type: hostpath
      #env: prod
