apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-secret-volume
spec:
  volumes:
  - name: mysecret-volume
    secret:
      secretName: mypassword
  containers:
  - name: nginx-ctr-volume
    image: nginx:latest
      #command: ["/bin/sh", "-c"]
      #args: ["env"]
    volumeMounts:
    - name: mysecret-volume
      mountPath: "/etc/password-mount-path"
