apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-env
spec:
  containers:
    - name: nginx-ctr
      image: nginx:latest
      env:
      - name: PASSWORD_ENV
        valueFrom:
          secretKeyRef:
            name: mypassword
            key: password.txt
