apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-configmap
spec:
  containers:
  - name: nginx-ctr
    image: nginx:latest
    env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: third-configmap
          key: color
