apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-all-configmap
spec:
  containers:
  - name: nginx-ctr
    image: nginx:latest
    command: ["/bin/sh", "-c"]
    args: ["env"]
    envFrom:
    - configMapRef:
        name: seventh-configmap
