apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "1Gi"
    limits.cpu: "1250m"
    limits.memory: "2Gi"
    configmaps: "10"
    services: "5"
