apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset-demo
spec:
  replicas: 3
  serviceName: nginx-headless
  selector:
    matchLabels:
      app: nginx-stateful
      env: test
  template:
    matadata:
      labels:
        app: nginx-stateful
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounths:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
        command:
        - /bin/sh
        - -c
        - |
          echo "You have been served by Pod with IP address: $(hostname -i)" > /usr/share/nginx/html/index.html
          nginx -g "deamon off";
    volumeClaimTemplates:
    - metadata:
        name: nginx-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


